/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedDemoRouteImport } from './routes/_authed/demo'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LoginCodeRouteImport } from './routes/login/code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDemoRoute = AuthedDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCodeRoute = LoginCodeRouteImport.update({
  id: '/login/code',
  path: '/login/code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof AuthedDemoRoute
  '/api/$': typeof ApiSplatRoute
  '/login/code': typeof LoginCodeRoute
  '/login/': typeof LoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof AuthedDemoRoute
  '/api/$': typeof ApiSplatRoute
  '/login/code': typeof LoginCodeRoute
  '/login': typeof LoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/demo': typeof AuthedDemoRoute
  '/api/$': typeof ApiSplatRoute
  '/login/code': typeof LoginCodeRoute
  '/login/': typeof LoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo' | '/api/$' | '/login/code' | '/login/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo' | '/api/$' | '/login/code' | '/login'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/demo'
    | '/api/$'
    | '/login/code'
    | '/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  LoginCodeRoute: typeof LoginCodeRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/demo': {
      id: '/_authed/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof AuthedDemoRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/code': {
      id: '/login/code'
      path: '/login/code'
      fullPath: '/login/code'
      preLoaderRoute: typeof LoginCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedDemoRoute: typeof AuthedDemoRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDemoRoute: AuthedDemoRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  LoginCodeRoute: LoginCodeRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
