// Sync apps/mobile/.env's identity from the repository .env.
//
// Why a script instead of a note: the app config (name, slug, scheme, bundle
// identifier) is part of the native runtime fingerprint, so a build made with
// one identity can never load an update published with another. Identity has
// exactly one source, the repository .env, and this mirrors it into the app's
// env where Expo reads it. Values the script does not own (EXPO_PUBLIC_API_URL
// and, after the ceremony, EAS_PROJECT_ID) are preserved verbatim.
//
//    bun run mobile:env
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const mobileEnvPath = join(root, "apps/mobile/.env");

const parseEnv = (text: string): Record<string, string> => {
  const values: Record<string, string> = {};
  for (const line of text.split("\n")) {
    const match = /^([A-Z0-9_]+)=(.*)$/.exec(line.trim());
    const key = match?.[1];
    // The repository .env may quote values (dotenv style, spaces survive);
    // the generated file should carry them unquoted.
    const value = match?.[2]?.replace(/^"(.*)"$/, "$1").replace(/^'(.*)'$/, "$1");
    if (key !== undefined && value !== undefined) values[key] = value;
  }
  return values;
};

const rootEnvPath = join(root, ".env");
const rootEnv = existsSync(rootEnvPath) ? parseEnv(readFileSync(rootEnvPath, "utf8")) : {};
const existing = existsSync(mobileEnvPath) ? parseEnv(readFileSync(mobileEnvPath, "utf8")) : {};

// Empty means "derive from the defaults": the same fallback the stack and the
// app config use, so a repository without identity values still runs.
const identity = {
  APP_NAME: rootEnv.APP_NAME ?? "",
  APP_SLUG: rootEnv.APP_SLUG ?? "",
  ROOT_DOMAIN: rootEnv.ROOT_DOMAIN ?? "",
};

const owned = ["EAS_PROJECT_ID", "EXPO_PUBLIC_API_URL"] as const;

writeFileSync(
  mobileEnvPath,
  [
    "# Generated by `bun run mobile:env` from the repository .env.",
    "# Identity must match the deployment, so edits to it are overwritten.",
    ...Object.entries(identity).map(([key, value]) => `${key}=${value}`),
    "",
    "# Local values, preserved across syncs:",
    ...owned.map((key) => `${key}=${existing[key] ?? ""}`),
    "",
  ].join("\n"),
);

console.log(`apps/mobile/.env synced from .env: ${JSON.stringify(identity)}`);
