// Sync apps/mobile/.env's identity from the repository .env.
//
// Why a script instead of a note: the app config (name, slug, scheme, bundle
// identifier) is part of the native runtime fingerprint, so a build made with
// one identity can never load an update published with another. Identity has
// exactly one source, the repository .env, and this mirrors it into the app's
// env where Expo reads it.
//
// Values are serialized so the file reads back byte-for-byte (a bare `Proof #2`
// would return as `Proof`), and blank identity is omitted rather than written
// empty: an `APP_SLUG=` line
// would defeat the defaults downstream (nullish coalescing does not catch empty
// strings), which is how an app once ended up with an empty scheme and a
// `dev.proof.` bundle identifier. Values the script does not own are preserved.
//
//    bun run mobile:env
import { existsSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { envValue, readEnvFile, resolveEnv, serializeEnvValue } from "./env.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const mobileEnvPath = join(root, "apps/mobile/.env");

const env = resolveEnv([join(root, ".env")]);
const identity: Record<string, string> = {};
for (const key of ["APP_NAME", "APP_SLUG", "ROOT_DOMAIN"] as const) {
  const value = envValue(env, key);
  if (value !== undefined) identity[key] = value;
}

// Local-only values the sync never authors, only carries forward.
const owned = ["EAS_PROJECT_ID", "EXPO_PUBLIC_API_URL"] as const;
const existing = existsSync(mobileEnvPath) ? readEnvFile(mobileEnvPath) : {};

writeFileSync(
  mobileEnvPath,
  [
    "# Generated by `bun run mobile:env` from the repository .env.",
    "# Identity must match the deployment, so edits to it are overwritten.",
    "# Blank values are omitted on purpose: absence means the app falls back",
    "# to its documented local defaults, while an empty value would break the",
    "# derived name, scheme, and bundle identifier.",
    ...Object.entries(identity).map(([key, value]) => `${key}=${serializeEnvValue(value)}`),
    "",
    "# Local values, preserved across syncs:",
    ...owned.map((key) => `${key}=${serializeEnvValue(envValue(existing, key) ?? "")}`),
    "",
  ].join("\n"),
);

console.log(`apps/mobile/.env synced from .env: ${JSON.stringify(identity)}`);
